export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SHOW_COMMENT_DIALOG = 'SHOW_COMMENT_DIALOG';
export const HIDE_COMMENT_DIALOG = 'HIDE_COMMENT_DIALOG';
export const SHOW_PROGRESS = 'SHOW_PROGRESS';
export const HIDE_PROGRESS = 'HIDE_PROGRESS';

